# Hardware related parameters
# will be loaded onto the parameter server
# See the diffbot.launch
diffbot:
  encoder_resolution: 1496
  gain: 1.0
  trim: 0.0
  motor_constant: 1.0 #27.0
  pwm_limit: 1.0
  debug:
    hardware_interface: false
    base_controller: true
  pid:
    pwm_min: 0.0 # PAS TOUCHE A DIT DD
    k_p: 20.0 # 7.5    1.75    5.0
    k_i: 5.0 
    k_d: 5.0