# Hardware related parameters
# will be loaded onto the parameter server
# See the diffbot.launch
diffbot:
  encoder_resolution: 1496
  gain: 1.0
  trim: 0.0
  motor_constant: 1.0 #27.0
  pwm_limit: 1.0
  debug:
    hardware_interface: false
    base_controller: true
  pid:
    pwm_min: 0 # PAS TOUCHE A DIT DD
    k_p: 34.7 #34.5
    k_i: 1.7 # 1.3
    k_d: 10  #1